use assert_fs::prelude::*;

use super::*;

#[test]
fn emit_bash_should_quote_single_quotes() {
    let vars = vec![("KEY".to_string(), "a'b".to_string())];
    let out = Env::emit_shell(agentstow_core::ShellKind::Bash, &vars).unwrap();
    assert!(out.contains("export KEY='a'\"'\"'b'"));
}

#[test]
fn emit_powershell_should_escape_single_quotes() {
    let vars = vec![("KEY".to_string(), "don't".to_string())];
    let out = Env::emit_shell(agentstow_core::ShellKind::Powershell, &vars).unwrap();
    assert!(out.contains("$Env:KEY = 'don''t'"));
}

#[test]
fn emit_cmd_should_wrap_assignment() {
    let vars = vec![("KEY".to_string(), "C:\\Program Files & Tools".to_string())];
    let out = Env::emit_shell(agentstow_core::ShellKind::Cmd, &vars).unwrap();
    assert!(out.starts_with("@REM Generated by agentstow (env emit)\n"));
    assert!(out.contains("set \"KEY=C:\\Program Files & Tools\""));
}

#[test]
fn emit_cmd_should_reject_runtime_expansion_chars() {
    let vars = vec![("KEY".to_string(), "100%".to_string())];
    let err = Env::emit_shell(agentstow_core::ShellKind::Cmd, &vars).unwrap_err();
    assert_eq!(err.exit_code(), agentstow_core::ExitCode::InvalidArgs);
    assert!(err.to_string().contains("Windows 上请优先使用 powershell"));
}

#[test]
fn resolve_env_set_should_reject_invalid_shell_key() {
    let env_set = agentstow_manifest::EnvSet {
        vars: vec![agentstow_manifest::EnvVarDef {
            key: "BAD-KEY".to_string(),
            binding: agentstow_core::SecretBinding::Literal {
                value: "x".to_string(),
            },
        }],
    };

    let err = Env::resolve_env_set(&env_set).unwrap_err();
    assert_eq!(err.exit_code(), agentstow_core::ExitCode::InvalidConfig);
    assert!(err.to_string().contains("env key 非法"));
}

#[test]
fn resolve_context_should_merge_files_and_inline_values() {
    let temp = assert_fs::TempDir::new().unwrap();
    temp.child(".env")
        .write_str("OWNER=platform-team\nDUPLICATE_ENV=from-dotenv\n")
        .unwrap();

    let env = agentstow_manifest::EnvContextDef {
        files: agentstow_manifest::EnvFilesDef {
            paths: vec![".env".into()],
        },
        emit: Default::default(),
        vars: std::collections::BTreeMap::from([
            ("DIRECT_ENV".to_string(), "from-inline".to_string()),
            ("DUPLICATE_ENV".to_string(), "from-manifest".to_string()),
        ]),
    };

    let vars = Env::resolve_context(&env, temp.path()).unwrap();
    assert_eq!(
        vars,
        vec![
            ("DIRECT_ENV".to_string(), "from-inline".to_string()),
            ("DUPLICATE_ENV".to_string(), "from-manifest".to_string()),
            ("OWNER".to_string(), "platform-team".to_string()),
        ]
    );
}

#[test]
fn emit_shell_should_preserve_newlines_inside_value() {
    let vars = vec![("KEY".to_string(), "line1\nline2".to_string())];
    let out = Env::emit_shell(agentstow_core::ShellKind::Bash, &vars).unwrap();
    assert!(out.contains("export KEY='line1\nline2'"));
}
