// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallMethodResponse } from "./InstallMethodResponse";

export type LinkRecordResponse = {
  artifact_id: string;
  profile: string;
  target_path: string;
  method: InstallMethodResponse;
  rendered_path: string | null;
  blake3: string | null;
  updated_at: string;
};
