// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManifestResponse = {
  workspace_root: string;
  profiles: Array<string>;
  artifacts: Array<string>;
  targets: Array<string>;
};
