use agentstow_core::{Result, ShellKind};
use agentstow_manifest::{EnvSet, EnvVarDef};
use tracing::instrument;

pub struct Env;

impl Env {
    #[instrument(skip_all)]
    pub fn resolve_env_set(env_set: &EnvSet) -> Result<Vec<(String, String)>> {
        let mut out = Vec::with_capacity(env_set.vars.len());
        for EnvVarDef { key, binding } in &env_set.vars {
            let value = binding.resolve()?;
            out.push((key.clone(), value));
        }
        Ok(out)
    }

    pub fn emit_shell(shell: ShellKind, vars: &[(String, String)]) -> Result<String> {
        let mut lines = Vec::new();
        lines.push("# Generated by agentstow (env emit)".to_string());
        match shell {
            ShellKind::Bash | ShellKind::Zsh => {
                for (k, v) in vars {
                    lines.push(format!("export {k}={}", posix_single_quote(v)));
                }
            }
            ShellKind::Fish => {
                for (k, v) in vars {
                    lines.push(format!("set -gx {k} {}", posix_single_quote(v)));
                }
            }
        }
        Ok(lines.join("\n") + "\n")
    }
}

fn posix_single_quote(s: &str) -> String {
    // 'foo' -> 'foo'
    // "a'b" -> 'a'"'"'b'
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\"'\"'");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests;
