use agentstow_core::{AgentStowError, Result, ShellKind};
use agentstow_manifest::{EnvSet, EnvVarDef};
use tracing::instrument;

pub struct Env;

impl Env {
    #[instrument(skip_all)]
    pub fn resolve_env_set(env_set: &EnvSet) -> Result<Vec<(String, String)>> {
        let mut out = Vec::with_capacity(env_set.vars.len());
        for EnvVarDef { key, binding } in &env_set.vars {
            validate_env_key(key)?;
            let value = binding.resolve()?;
            out.push((key.clone(), value));
        }
        Ok(out)
    }

    pub fn emit_shell(shell: ShellKind, vars: &[(String, String)]) -> Result<String> {
        let mut lines = Vec::new();
        lines.push(shell_header(shell).to_string());
        match shell {
            ShellKind::Bash | ShellKind::Zsh => {
                for (k, v) in vars {
                    lines.push(format!("export {k}={}", posix_single_quote(v)));
                }
            }
            ShellKind::Fish => {
                for (k, v) in vars {
                    lines.push(format!("set -gx {k} {}", posix_single_quote(v)));
                }
            }
            ShellKind::Powershell => {
                for (k, v) in vars {
                    lines.push(format!("$Env:{k} = {}", powershell_single_quote(v)));
                }
            }
            ShellKind::Cmd => {
                for (k, v) in vars {
                    lines.push(format!("set \"{k}={}\"", cmd_batch_value(v)?));
                }
            }
        }
        Ok(lines.join("\n") + "\n")
    }
}

fn shell_header(shell: ShellKind) -> &'static str {
    match shell {
        ShellKind::Cmd => "@REM Generated by agentstow (env emit)",
        ShellKind::Bash | ShellKind::Zsh | ShellKind::Fish | ShellKind::Powershell => {
            "# Generated by agentstow (env emit)"
        }
    }
}

fn posix_single_quote(s: &str) -> String {
    // 'foo' -> 'foo'
    // "a'b" -> 'a'"'"'b'
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\"'\"'");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

fn powershell_single_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

fn cmd_batch_value(s: &str) -> Result<String> {
    if s.contains(['\0', '\r', '\n', '"', '%', '!']) {
        return Err(AgentStowError::InvalidArgs {
            message: "cmd env emit 暂不支持包含 NUL/换行/双引号/%/! 的值；Windows 上请优先使用 powershell".into(),
        });
    }

    Ok(s.to_string())
}

fn validate_env_key(key: &str) -> Result<()> {
    let mut chars = key.chars();
    let Some(first) = chars.next() else {
        return Err(AgentStowError::Manifest {
            message: "env key 不能为空".into(),
        });
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return Err(AgentStowError::Manifest {
            message: format!("env key 非法: {key}（必须匹配 [A-Za-z_][A-Za-z0-9_]*）").into(),
        });
    }
    if chars.any(|ch| !(ch.is_ascii_alphanumeric() || ch == '_')) {
        return Err(AgentStowError::Manifest {
            message: format!("env key 非法: {key}（必须匹配 [A-Za-z_][A-Za-z0-9_]*）").into(),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests;
