// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactSourceResponse } from "./ArtifactSourceResponse";
import type { GitCommitSummaryResponse } from "./GitCommitSummaryResponse";

export type ArtifactGitRollbackResponse = {
  artifact_id: string;
  commit: GitCommitSummaryResponse;
  source: ArtifactSourceResponse;
};
