// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitCommitSummaryResponse } from "./GitCommitSummaryResponse";

export type ArtifactGitHistoryResponse = {
  artifact_id: string;
  source_path: string;
  repo_relative_path: string;
  branch: string | null;
  head: string;
  head_short: string;
  dirty: boolean;
  commits: Array<GitCommitSummaryResponse>;
};
