// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactGitCompareResponse = {
  artifact_id: string;
  source_path: string;
  repo_relative_path: string;
  base_revision: string;
  head_revision: string;
  base_label: string;
  head_label: string;
  base_content: string;
  head_content: string;
  changed: boolean;
};
