// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactKindResponse } from "./ArtifactKindResponse";
import type { ValidateAsResponse } from "./ValidateAsResponse";

export type ArtifactSourceResponse = {
  artifact_id: string;
  kind: ArtifactKindResponse;
  source_path: string;
  template: boolean;
  validate_as: ValidateAsResponse;
  content: string;
};
