// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactSummaryResponse } from "./ArtifactSummaryResponse";
import type { ProfileSummaryResponse } from "./ProfileSummaryResponse";
import type { TargetSummaryResponse } from "./TargetSummaryResponse";
import type { ValidationIssueResponse } from "./ValidationIssueResponse";

export type ArtifactDetailResponse = {
  artifact: ArtifactSummaryResponse;
  targets: Array<TargetSummaryResponse>;
  profiles: Array<ProfileSummaryResponse>;
  issues: Array<ValidationIssueResponse>;
};
