// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvUsageRefResponse } from "./EnvUsageRefResponse";
import type { EnvVarSummaryResponse } from "./EnvVarSummaryResponse";

export type EnvEmitSetSummaryResponse = {
  id: string;
  vars: Array<EnvVarSummaryResponse>;
  available_count: number;
  missing_count: number;
  referrers: Array<EnvUsageRefResponse>;
};
