// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShellKindResponse } from "./ShellKindResponse";

export type EnvEmitRequest = { set: string | null; shell: ShellKindResponse };
