// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVarSummaryResponse } from "./EnvVarSummaryResponse";

export type EnvSetSummaryResponse = {
  id: string;
  vars: Array<EnvVarSummaryResponse>;
};
