// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvUsageOwnerKindResponse } from "./EnvUsageOwnerKindResponse";

export type EnvUsageRefResponse = {
  owner_kind: EnvUsageOwnerKindResponse;
  owner_id: string;
  label: string;
};
