// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvUsageRefResponse } from "./EnvUsageRefResponse";
import type { SecretBindingKindResponse } from "./SecretBindingKindResponse";

export type EnvVarSummaryResponse = {
  key: string;
  binding: string;
  binding_kind: SecretBindingKindResponse;
  source_env_var: string | null;
  rendered_placeholder: string;
  available: boolean;
  diagnostic: string | null;
  referrers: Array<EnvUsageRefResponse>;
};
