// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitCommitSummaryResponse = {
  revision: string;
  short_revision: string;
  summary: string;
  author_name: string;
  authored_at: string;
};
