// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactSummaryResponse } from "./ArtifactSummaryResponse";
import type { ImpactSubjectKindResponse } from "./ImpactSubjectKindResponse";
import type { LinkStatusResponseItem } from "./LinkStatusResponseItem";
import type { ProfileSummaryResponse } from "./ProfileSummaryResponse";
import type { TargetSummaryResponse } from "./TargetSummaryResponse";
import type { ValidationIssueResponse } from "./ValidationIssueResponse";

export type ImpactAnalysisResponse = {
  subject_kind: ImpactSubjectKindResponse;
  subject_id: string;
  affected_targets: Array<TargetSummaryResponse>;
  affected_artifacts: Array<ArtifactSummaryResponse>;
  affected_profiles: Array<ProfileSummaryResponse>;
  link_status: Array<LinkStatusResponseItem>;
  issues: Array<ValidationIssueResponse>;
};
