// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkPlanRequest = {
  /**
   * 可选：为空则对所有 targets 生效
   */
  targets: Array<string>;
  /**
   * target 未声明 profile 时可用（等价于 CLI 的全局 --profile）
   */
  default_profile: string | null;
};
