// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkOperationItemResponse } from "./LinkOperationItemResponse";

export type LinkOperationResponse = { items: Array<LinkOperationItemResponse> };
