// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkOperationActionResponse } from "./LinkOperationActionResponse";
import type { LinkPlanItemResponse } from "./LinkPlanItemResponse";

export type LinkOperationItemResponse = {
  action: LinkOperationActionResponse;
  item: LinkPlanItemResponse;
  message: string | null;
};
