// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkDesiredInstallResponse =
  | { "kind": "symlink"; source_path: string }
  | { "kind": "junction"; source_path: string }
  | { "kind": "copy"; blake3: string; bytes_len: number };
