// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallMethodResponse } from "./InstallMethodResponse";

export type LinkStatusResponseItem = {
  artifact_id: string;
  profile: string;
  target_path: string;
  method: InstallMethodResponse;
  ok: boolean;
  message: string;
};
