// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactKindResponse } from "./ArtifactKindResponse";
import type { InstallMethodResponse } from "./InstallMethodResponse";
import type { LinkDesiredInstallResponse } from "./LinkDesiredInstallResponse";

export type LinkPlanItemResponse = {
  target: string;
  artifact_id: string;
  profile: string;
  artifact_kind: ArtifactKindResponse;
  method: InstallMethodResponse;
  target_path: string;
  desired: LinkDesiredInstallResponse;
};
