// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpCheckStatusResponse } from "./McpCheckStatusResponse";

export type McpCheckResponse = {
  code: string;
  status: McpCheckStatusResponse;
  message: string;
  detail: string | null;
};
