// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVarSummaryResponse } from "./EnvVarSummaryResponse";
import type { McpTransportKindResponse } from "./McpTransportKindResponse";

export type McpRenderResponse = {
  server_id: string;
  transport_kind: McpTransportKindResponse;
  launcher_preview: string;
  config_json: string;
  env_bindings: Array<EnvVarSummaryResponse>;
};
