// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpTransportKindResponse } from "./McpTransportKindResponse";

export type McpServerSummaryResponse = {
  id: string;
  transport_kind: McpTransportKindResponse;
  location: string;
  env_keys: Array<string>;
};
