// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVarSummaryResponse } from "./EnvVarSummaryResponse";
import type { McpHeaderResponse } from "./McpHeaderResponse";
import type { McpTransportKindResponse } from "./McpTransportKindResponse";

export type McpServerSummaryResponse = {
  id: string;
  transport_kind: McpTransportKindResponse;
  location: string;
  command: string | null;
  args: Array<string>;
  url: string | null;
  headers: Array<McpHeaderResponse>;
  env_keys: Array<string>;
  env_bindings: Array<EnvVarSummaryResponse>;
};
