// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpCheckResponse } from "./McpCheckResponse";

export type McpTestResponse = {
  server_id: string;
  ok: boolean;
  checks: Array<McpCheckResponse>;
};
