// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationIssueResponse } from "./ValidationIssueResponse";

export type McpValidateResponse = {
  server_id: string;
  ok: boolean;
  issues: Array<ValidationIssueResponse>;
};
