// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactSummaryResponse } from "./ArtifactSummaryResponse";
import type { ProfileSummaryResponse } from "./ProfileSummaryResponse";
import type { ProfileVarResponse } from "./ProfileVarResponse";
import type { TargetSummaryResponse } from "./TargetSummaryResponse";
import type { ValidationIssueResponse } from "./ValidationIssueResponse";

export type ProfileDetailResponse = {
  profile: ProfileSummaryResponse;
  merged_vars: Array<ProfileVarResponse>;
  targets: Array<TargetSummaryResponse>;
  artifacts: Array<ArtifactSummaryResponse>;
  issues: Array<ValidationIssueResponse>;
};
