// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileSummaryResponse = {
  id: string;
  extends: Array<string>;
  variable_keys: Array<string>;
  target_ids: Array<string>;
  artifact_ids: Array<string>;
};
