// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScriptRunResponse = {
  exit_code: number;
  stdout: string | null;
  stderr: string | null;
};
