// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScriptSummaryResponse = {
  id: string;
  kind: string;
  entry: string;
  args: Array<string>;
  env_keys: Array<string>;
  timeout_ms: bigint | null;
};
