// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CwdPolicyResponse } from "./CwdPolicyResponse";
import type { EnvVarSummaryResponse } from "./EnvVarSummaryResponse";
import type { OutputModeResponse } from "./OutputModeResponse";
import type { StdinModeResponse } from "./StdinModeResponse";

export type ScriptSummaryResponse = {
  id: string;
  kind: string;
  entry: string;
  args: Array<string>;
  cwd_policy: CwdPolicyResponse;
  env_keys: Array<string>;
  env_bindings: Array<EnvVarSummaryResponse>;
  stdin_mode: StdinModeResponse;
  stdout_mode: OutputModeResponse;
  stderr_mode: OutputModeResponse;
  timeout_ms: number | null;
  expected_exit_codes: Array<number>;
};
