// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallMethodResponse } from "./InstallMethodResponse";

export type TargetSummaryResponse = {
  id: string;
  artifact_id: string;
  profile: string | null;
  target_path: string;
  method: InstallMethodResponse;
};
