// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchModeResponse } from "./WatchModeResponse";

export type WatchStatusResponse = {
  mode: WatchModeResponse;
  healthy: boolean;
  revision: number;
  poll_interval_ms: number | null;
  last_event: string | null;
  last_event_at: string | null;
  last_error: string | null;
  watch_roots: Array<string>;
};
