// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceCountsResponse = {
  profile_count: number;
  artifact_count: number;
  target_count: number;
  env_emit_set_count: number;
  script_count: number;
  mcp_server_count: number;
  link_count: number;
  healthy_link_count: number;
  unhealthy_link_count: number;
};
