// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceGitSummaryResponse = {
  repo_root: string;
  branch: string | null;
  head: string;
  head_short: string;
  dirty: boolean;
};
