// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceProbeResponse } from "./WorkspaceProbeResponse";

export type WorkspaceInitResponse = {
  workspace_root: string;
  manifest_path: string;
  created: boolean;
  workspace: WorkspaceProbeResponse;
};
