// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceProbeResponse = {
  requested_workspace_root: string;
  resolved_workspace_root: string;
  exists: boolean;
  is_directory: boolean;
  manifest_present: boolean;
  manifest_path: string;
  git_present: boolean;
  selectable: boolean;
  initializable: boolean;
  reason: string | null;
};
