// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactSummaryResponse } from "./ArtifactSummaryResponse";
import type { EnvSetSummaryResponse } from "./EnvSetSummaryResponse";
import type { McpServerSummaryResponse } from "./McpServerSummaryResponse";
import type { ProfileSummaryResponse } from "./ProfileSummaryResponse";
import type { ScriptSummaryResponse } from "./ScriptSummaryResponse";
import type { TargetSummaryResponse } from "./TargetSummaryResponse";
import type { ValidationIssueResponse } from "./ValidationIssueResponse";
import type { WorkspaceCountsResponse } from "./WorkspaceCountsResponse";

export type WorkspaceSummaryResponse = {
  workspace_root: string;
  counts: WorkspaceCountsResponse;
  profiles: Array<ProfileSummaryResponse>;
  artifacts: Array<ArtifactSummaryResponse>;
  targets: Array<TargetSummaryResponse>;
  env_sets: Array<EnvSetSummaryResponse>;
  scripts: Array<ScriptSummaryResponse>;
  mcp_servers: Array<McpServerSummaryResponse>;
  issues: Array<ValidationIssueResponse>;
};
