use assert_fs::prelude::*;
use pretty_assertions::assert_eq;
use serial_test::serial;

use super::fixtures::{
    block_on, test_server, with_test_home, write_prd_workspace, write_script_workspace,
};

#[test]
#[serial]
fn api_env_emit_should_generate_shell_script_for_env_set() {
    let temp = assert_fs::TempDir::new().unwrap();
    write_prd_workspace(&temp);

    with_test_home(&temp, || {
        temp_env::with_var("OPENAI_API_KEY", Some("token123"), || {
            block_on(async {
                let server = test_server(&temp, temp.child("missing-dist").path().to_path_buf());

                let resp = server
                    .post("/api/env/emit")
                    .json(&serde_json::json!({
                        "env_set_id": "default",
                        "shell": "bash",
                    }))
                    .await;

                resp.assert_status_ok();
                let body: serde_json::Value = resp.json();
                let text = body["text"].as_str().unwrap();
                assert!(text.contains("Generated by agentstow"));
                assert!(text.contains("export OPENAI_API_KEY='token123'"));
            });
        });
    });
}

#[tokio::test]
async fn api_scripts_run_should_execute_manifest_script_and_return_output() {
    let temp = assert_fs::TempDir::new().unwrap();
    write_script_workspace(&temp);

    let server = test_server(&temp, temp.child("missing-dist").path().to_path_buf());
    let resp = server
        .post("/api/scripts/hello/run")
        .json(&serde_json::json!({ "stdin": null }))
        .await;

    resp.assert_status_ok();
    let body: serde_json::Value = resp.json();
    assert_eq!(body["exit_code"], serde_json::json!(0));
    let stdout = body["stdout"].as_str().unwrap();
    assert_eq!(stdout.trim(), "hello");
}
