[profiles.base]
vars = { owner = "platform-team", workspace_name = "codex-lab", default_profile = "base" }

## Context

[env.files]     # 这个是能够将文件内容解析为环境变量的功能, 这个键是程序保留的
paths = [".env"]

[env]
THIS_IS_ENV = "true"
DIRECT_ENV = "可以直接在这里声明环境变量，或者通过上面的 env.files 从文件中加载环境变量"
DUPLICATE_ENV = "如果同一个环境变量在这里和 env.files 中都有声明，那么以这里为准, 覆盖掉 env.files 中的声明"

[env.emit.demo]
vars = [
  { key = "WORKSPACE_NAME", binding = { kind = "literal", value = "codex-lab" } },
  { key = "WORKSPACE_OWNER", binding = { kind = "literal", value = "platform-team" } }
]

[file.reference] # 这里是将这个 reference.md 文件作为可以被引用解析和注入的文件
path = "reference.md"

[file.worker_description]
path = "templates/agents/descriptions/worker.md"

[file.explorer_description]
path = "templates/agents/descriptions/explorer.md"

[mcp_servers.file] # 这个是能够将 json 格式的 mcp 配置文件也解析作为 mcp servers, 这个键是程序保留的
path = "mcps.json" # 这里的 mcps.json 文件内容需要符合 MCP Server 的配置格式, 解析后会将其中的 MCP Server 配置注入到 mcp_servers 中, 以供后续引用和使用

[mcp_servers.sequential_thinking] # 这个就是一个直接声明的 mcp server, 在后续引用的时候需要用到
transport = { kind = "stdio", command = "bunx", args = ["-y", "@modelcontextprotocol/server-sequential-thinking"] }

[mcp_servers.tavily]
transport = { kind = "http", url = "https://mcp.tavily.com/mcp" }
env = [
  { key = "TAVILY_API_KEY", binding = { kind = "env", var = "TAVILY_API_KEY" } }
]

[mcp_servers.ace_tool]
transport = { kind = "http", url = "https://acemcp.heroman.wtf/relay/" }
env = [
  { key = "ACE_TOOL_TOKEN", binding = { kind = "env", var = "ACE_TOOL_TOKEN" } }
]

#### Artifacts

[artifacts.workspace_agents]
kind = "file"
source = "templates/AGENTS.md.tera"
template = true
validate_as = "none"

[artifacts.agents_dir]
kind = "dir"
source = "templates/agents"
template = true

[artifacts.dotenv]
kind = "file"
source = "templates/dotenv.tera"
template = true
validate_as = "none"

#### Targets

[targets.workspace_agents_copy]
artifact = "workspace_agents"
profile = "base"
target_path = "demo-targets/codex-lab/AGENTS.md"
method = "copy"

[targets.agents_dir_primary]
artifact = "agents_dir"
profile = "base"
target_path = "demo-targets/codex-lab/.agents"
method = "symlink"

[targets.dotenv_primary]
artifact = "dotenv"
profile = "base"
target_path = "demo-targets/codex-lab/.env"
method = "symlink"

[targets.workspace_agents_symlink]
artifact = "workspace_agents"
profile = "base"
target_path = "demo-targets-2/AGENTS.md"
method = "symlink"

[targets.agents_dir_symlink]
artifact = "agents_dir"
profile = "base"
target_path = "demo-targets-2/.agents"
method = "symlink"

[targets.dotenv_symlink]
artifact = "dotenv"
profile = "base"
target_path = "demo-targets-2/.env"
method = "symlink"

